sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '4'
  - '0.12'
  - '0.10'

before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
after_script:
  - npm run -s coveralls
after_success:
  - npm run -s semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
